name: User Workflow

on: 
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with: 
                persist-credentials: false
              
            - name: Reusable Workflow
              uses: ./internal/rbb
              with:
                repo_path: "./cc_bazel_test"     #USER INPUTTED MATERIAL??? wonder if can grab it from checkout
                targets: "//src:fib //src:hello" #USER INPUTTED MATERIAL

            - name: Download Binaries
              uses: actions/download-artifact@v3
              with:
                name: binaries
        
                
